### ISSUE TITLE
LiveFilters should make use of the DAQ SVN repositories

### ISSUE THREAD

**Issue by cwipf** [cwipf/SimulinkNb#11]

**Comment by cwipf** [comment]
Fixed in commit b22561787a1c8b1133ff1c314d244111666261fa

**Comment by astaley** [comment]
Hey Chris,

Is this related to that remotely we have to pick the correct DAQ svn revision for the live parts? 

Also nice work with the MICH loop!

Thanks,

Alexa

**Comment by cwipf** [comment]
Yes, that's what this bug was about. There should be no more need to monkey with checking out the DAQ SVN at a specific revision.

**Comment by astaley** [comment]
Awesome! Thanks Chris. 

Alexa
