### ISSUE TITLE
Adding noises out of model scheme

### ISSUE THREAD

**Issue by michal-was** [cwipf/SimulinkNb#18]
Noises where the way it enters the system is not modeled in Simulink cannot easily be added. For example an angular noise, where the feed-back spectrum is recorded, and the transfer function can be measured (but is not understood).

An easy first step is to add a field in the noise source block, that makes the code skip applying the computed transfer function sys(n+2)*cal (line 167 in nbFromSimulink.m). A second step would be to use that field to provide a transfer function to use instead. Of course if that field is left blank the code would use the model transfer function sys(n+2)*cal.

**Comment by cwipf** [comment]
Pasting from an email thread about this bug:

It seems we don't need to change the code to support adding measured noise couplings.  If you sum in a noise source block at the same point in your model as the cal block, then sys(n+2)*cal = 1, i.e. the noise source's ASD is assumed to be already calibrated.  If you have your own measured calibration TF, then you can send the noise source through a FlexTf block before summing it in, and the code will apply the TF for you.
